### ISSUE TITLE
기본 주제

### ISSUE THREAD

**Issue by wlxyzlw** [NaverSnu-MusicProject/-#2]
# 공간 기반 음악 추천 웹 어플리케이션 만들기

저번 회의록 기준으로 설명 추가바람

**Comment by wlxyzlw** [comment]
3차 회의의 결과로 다음과 같은 주제를 정했습니다.
# 공간 기반 뮤직 큐레이션 웹 어플리케이션 만들기
## GPS, API, 휴대폰 자체 status를 이용하여
### 명사형 -> 형용사형

**Comment by alphecca** [comment]
3/13에 주제를 정하였으므로 닫습니다
주제는 4차 회의록(0313.md) 을 참고해주세요
