### ISSUE TITLE
회의록

### ISSUE THREAD

**Issue by wlxyzlw** [NaverSnu-MusicProject/-#3]
@alphecca 저번에 네이버 가서 회의한거랑 오늘 내일 회의할 거를 올려봅시당

**Comment by alphecca** [comment]
네 meetings 폴더를 만들어서 올리면 편할 듯한데, 모바일로는 곤란하네요
내일 회의전까지 금요일 회의록 올리도록 하겠습니다

**Comment by wlxyzlw** [comment]
회의록을 잘 올리고 있습니다.
closed #3
